#!/usr/bin/env python3
"""Report provenance quality for curated sources and evidence-bearing model notes.

This is intentionally report-only. Findings do not fail the build.
"""
from __future__ import annotations
import re
from pathlib import Path
from collections import Counter
try:
    import yaml
except ImportError:
    raise SystemExit("PyYAML is required")

ROOT=Path(__file__).resolve().parents[2]
REPORT=ROOT/"provenance-quality-report.md"

def fm(text):
    if not text.startswith("---\n"): return {}
    end=text.find("\n---",4)
    if end<0: return {}
    try: return yaml.safe_load(text[4:end]) or {}
    except Exception: return {}

def vals(v):
    if v is None: return []
    return v if isinstance(v,list) else [v]

notes=[]
for p in ROOT.rglob("*.md"):
    if ".git" in p.parts or "99_System" in p.parts: continue
    rel=p.relative_to(ROOT).as_posix()
    text=p.read_text(encoding="utf-8",errors="replace")
    data=fm(text)
    if isinstance(data,dict) and data.get("type"):
        notes.append((rel,text,data))

source_records=[]
claim_notes=[]
for rel,text,data in notes:
    tags=[str(x) for x in vals(data.get("tags"))]
    if data.get("type")=="Document" and "source-document" in tags:
        source_records.append((rel,text,data))
    evidence_signal=bool(re.search(r"(?im)^\s*[-*]?\s*\*\*Source(?:s)?(?: identity)?[^:]*:\*\*|\bSource:\s*https?://|https?://",text))
    if evidence_signal and "source-document" not in tags:
        claim_notes.append((rel,text,data))

source_rows=[]
for rel,text,data in source_records:
    missing_required=[]
    for key in ("sourceClass","sourceUrl"):
        if not data.get(key): missing_required.append(key)
    optional_unknown=[]
    for key in ("sourceRevision","accessed"):
        if not data.get(key): optional_unknown.append(key)
    body_checks={
        "local artifact": bool(re.search(r"(?im)^- \*\*Local artifact:\*\*",text)),
        "source identity": bool(re.search(r"(?im)^- \*\*Source identity:\*\*",text)),
        "original web address": bool(re.search(r"(?im)^- \*\*Original web address:\*\*",text)),
        "document date/revision": bool(re.search(r"(?im)^- \*\*Document date / revision:\*\*",text)),
        "review/access context": bool(re.search(r"(?im)^- \*\*(?:Local copy reviewed|Original web access/download date):\*\*",text)),
    }
    missing_body=[k for k,v in body_checks.items() if not v]
    unknown_access=bool(re.search(r"(?im)Original web access/download date:\*\*\s*Not recorded",text))
    source_rows.append((rel,missing_required,optional_unknown,missing_body,unknown_access))

claim_rows=[]
for rel,text,data in claim_notes:
    links=[]
    for key in ("supportedBy","referencedBy","describedBy"):
        links.extend(str(x) for x in vals(data.get(key)) if x)
    has_curated_link=bool(links)
    raw_urls=len(re.findall(r"https?://[^\s)>]+",text))
    claim_rows.append((rel,raw_urls,has_curated_link,links))

summary={
    "model_notes":len(notes),
    "source_records":len(source_records),
    "source_records_missing_required_structured_provenance":sum(1 for _,m,___,____,_____ in source_rows if m),
    "source_records_without_optional_source_revision":sum(1 for _,__,u,___,____ in source_rows if "sourceRevision" in u),
    "source_records_without_recorded_accessed":sum(1 for _,__,u,___,____ in source_rows if "accessed" in u),
    "source_records_missing_legacy_body_provenance_signals":sum(1 for _,__,___,m,____ in source_rows if m),
    "source_records_explicitly_unknown_original_access_date":sum(1 for *_,u in source_rows if u),
    "evidence_signal_notes":len(claim_notes),
    "evidence_signal_notes_without_curated_link":sum(1 for _,_,h,_ in claim_rows if not h),
    "evidence_signal_notes_with_curated_link":sum(1 for _,_,h,_ in claim_rows if h),
}

lines=["# PosiBattery Provenance Quality Report","",
"Report-only quality scan generated by `99_System/09_Tools/report-provenance.py`. Findings are review prompts, not structural failures.","",
"## Summary","",
"| Check | Count |","|---|---:|"]
for k,v in summary.items(): lines.append(f"| {k.replace('_',' ')} | {v} |")

lines += ["","## Curated Source Document records","",
"| Source record | Missing required structured fields | Optional structured fields not recorded | Missing legacy body signals | Original web access explicitly unknown |",
"|---|---|---|---|---|"]
for rel,mr,ou,mb,u in source_rows:
    lines.append(f"| {rel} | {', '.join(mr) if mr else 'None'} | {', '.join(ou) if ou else 'None'} | {', '.join(mb) if mb else 'None'} | {'Yes' if u else 'No'} |")

lines += ["","## Evidence-bearing notes without curated evidence linkage","",
"These notes contain source/URL evidence signals but do not currently expose `supportedBy`, `referencedBy`, or `describedBy` in frontmatter. A raw URL may still be valid evidence; this section identifies candidates for later curation, not errors.","",
"| Note | Raw URL count |","|---|---:|"]
unlinked=[x for x in claim_rows if not x[2]]
for rel,count,_,__ in unlinked[:300]:
    lines.append(f"| {rel} | {count} |")
if len(unlinked)>300: lines.append(f"| … | {len(unlinked)-300} additional notes omitted from display |")

lines += ["","## Interpretation","",
"- For curated Source Documents, sourceClass and sourceUrl are the required structured provenance fields used by the semantic-linking review. sourceRevision and accessed are optional when the source/repository history does not establish them.",
"- Legacy body-provenance labels are recognized separately from structured YAML. Missing legacy body labels are diagnostic only when required structured provenance is present.",
"- Evidence-bearing notes are detected heuristically from source labels and URLs; this does not prove every URL is a material engineering claim.",
"- Do not invent access dates, revisions, or source identity. Add them only when supported by the source or repository history.",
""]
REPORT.write_text("\n".join(lines),encoding="utf-8")
print("provenance quality reporting")
for k,v in summary.items(): print(f"  {k.replace('_',' ')}: {v}")
print(f"  report: {REPORT.relative_to(ROOT)}")
print("PROVENANCE REPORT GENERATED (REPORT-ONLY)")
